create table profile_key_master( 
  _id integer primary key autoincrement, 
  name text not null, 
  description text, 
  sort_order integer not null default 0, 
  plural_flg integer not null default 0, 
  value_type_id integer not null, 
  initial_value text, 
  system_flg integer not null default 0, 
  use_flg integer not null default 1,
  option00 text,
  option01 text,
  option02 text,
  option03 text,
  option04 text,
  option05 text,
  option06 text,
  option07 text,
  option08 text,
  option09 text,
  option10 text,
  option11 text,
  option12 text,
  option13 text,
  option14 text,
  option15 text,
  option16 text,
  option17 text,
  option18 text,
  option19 text
);