insert into profile_key_master values ( 1,'名前'           ,'',2,0,2,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values ( 2,'よみがな'       ,'',3,0,2,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values ( 3,'ニックネーム'   ,'',4,0,2,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values ( 4,'誕生日'         ,'',5,0,6,'1980/01/01',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values ( 5,'写真'           ,'',1,0,7,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values ( 6,'出身地'         ,'',6,0,2,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values ( 7,'血液型'         ,'',7,0,5,'',0,1,"A型","B型","O型","AB型",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values ( 8,'仕事'           ,'',8,0,2,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values ( 9,'靴のサイズ'     ,'',9,0,1,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values (10,'好きな食べ物'  ,'',10,0,2,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values (11,'好きな映画'    ,'',11,0,2,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values (12,'好きなアニメ'  ,'',12,0,2,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values (13,'好きな音楽'    ,'',13,0,2,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values (14,'好きな色'      ,'',14,0,2,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values (15,'嫌いなもの'    ,'',15,0,2,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values (16,'地雷ワード'    ,'',16,0,2,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into profile_key_master values (17,'フェチ'        ,'',17,0,2,'',0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);